### ISSUE TITLE
Docker container fails to run on macos

### ISSUE THREAD

**Issue by neurohacker** [openworm/OpenWorm#272]
```
ow@267366ab2e6c:~$ DISPLAY=:44 python master_openworm.py
Traceback (most recent call last):
  File "master_openworm.py", line 3, in <module>
    import matplotlib
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 33, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 5, in <module>
    from .info import __doc__
  File "/usr/lib/python2.7/dist-packages/numpy/lib/info.py", line 1
SyntaxError: Non-ASCII character '\xca' in file /usr/lib/python2.7/dist-packages/numpy/lib/info.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by mahakkothari** [comment]
is this issue already solved?
because I am not getting error like this

**Comment by mwatts15** [comment]
Hi, @neurohacker . That's odd, but it doesn't appear to be Mac OSX-specific. It actually looks like either a numpy issue or an Ubuntu issue.

Could you try just rebuilding the docker image with the `--no-cache` option and see if that error still shows up? I know it takes a while to re-download everything, but I'm betting the issue is transient. I'll try to reproduce on my machine as well.

**Comment by mwatts15** [comment]
I've attempted a limited reproduction with a new container, installing python-matplotlib and importing matplotlib, but it imports fine. If you experience the issue on a new container, please re-open this issue.
